#!/usr/bin/env python3
"""
Script to generate JavaScript text configuration from JSON file.
This ensures the JavaScript configuration stays in sync with the JSON configuration.
"""

import json
import os
import sys
from pathlib import Path

def generate_js_config(json_file_path, output_file_path):
    """Generate JavaScript configuration from JSON file."""
    
    # Read the JSON configuration
    try:
        with open(json_file_path, 'r', encoding='utf-8') as f:
            config = json.load(f)
    except FileNotFoundError:
        print(f"Error: JSON configuration file not found at {json_file_path}")
        return False
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in configuration file: {e}")
        return False
    
    # Generate JavaScript content
    js_content = f'''/**
 * Text configuration for Validex frontend
 * This file is auto-generated from {os.path.basename(json_file_path)}
 * Do not edit this file directly - edit the JSON configuration instead
 */

window.TextConfig = {json.dumps(config, indent=4)};

/**
 * Helper function to get text values
 * @param {{string}} keyPath - Dot-separated path to the text value
 * @param {{string}} defaultValue - Default value if key is not found
 * @returns {{string}} The text value or default if not found
 */
window.getText = function(keyPath, defaultValue = "") {{
    const keys = keyPath.split('.');
    let value = window.TextConfig;
    
    try {{
        for (const key of keys) {{
            value = value[key];
        }}
        return value !== undefined ? String(value) : defaultValue;
    }} catch (error) {{
        return defaultValue;
    }}
}};

/**
 * Helper function to get text values with fallback
 * @param {{string}} keyPath - Dot-separated path to the text value
 * @param {{string}} fallbackKeyPath - Fallback key path
 * @param {{string}} defaultValue - Default value if both keys are not found
 * @returns {{string}} The text value or default if not found
 */
window.getTextWithFallback = function(keyPath, fallbackKeyPath, defaultValue = "") {{
    const primary = window.getText(keyPath, null);
    if (primary !== null) {{
        return primary;
    }}
    return window.getText(fallbackKeyPath, defaultValue);
}};
'''
    
    # Write the JavaScript file
    try:
        # Ensure the output directory exists
        os.makedirs(os.path.dirname(output_file_path), exist_ok=True)
        
        with open(output_file_path, 'w', encoding='utf-8') as f:
            f.write(js_content)
        
        print(f"Successfully generated JavaScript configuration at {output_file_path}")
        return True
        
    except Exception as e:
        print(f"Error writing JavaScript configuration: {e}")
        return False

def main():
    """Main function."""
    # Get project root directory
    project_root = Path(__file__).parent.parent
    
    # Define file paths
    json_file = project_root / 'config' / 'text_config.json'
    js_file = project_root / 'app' / 'static' / 'js' / 'text-config.js'
    
    # Generate the JavaScript configuration
    success = generate_js_config(str(json_file), str(js_file))
    
    if success:
        print("Text configuration generation completed successfully!")
        sys.exit(0)
    else:
        print("Text configuration generation failed!")
        sys.exit(1)

if __name__ == '__main__':
    main()


